// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: moca/payment/delayed_withdrawal_record.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DelayedWithdrawalRecord struct {
	// the withdrawal address
	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// the withdrawal amount
	Amount cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
	// the withdrawal from payment account address
	From string `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	// unlock timestamp is the unix timestamp to unlock the withdrawal
	UnlockTimestamp int64 `protobuf:"varint,4,opt,name=unlock_timestamp,json=unlockTimestamp,proto3" json:"unlock_timestamp,omitempty"`
}

func (m *DelayedWithdrawalRecord) Reset()         { *m = DelayedWithdrawalRecord{} }
func (m *DelayedWithdrawalRecord) String() string { return proto.CompactTextString(m) }
func (*DelayedWithdrawalRecord) ProtoMessage()    {}
func (*DelayedWithdrawalRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bf591a176352bb4, []int{0}
}
func (m *DelayedWithdrawalRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelayedWithdrawalRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelayedWithdrawalRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelayedWithdrawalRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelayedWithdrawalRecord.Merge(m, src)
}
func (m *DelayedWithdrawalRecord) XXX_Size() int {
	return m.Size()
}
func (m *DelayedWithdrawalRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DelayedWithdrawalRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DelayedWithdrawalRecord proto.InternalMessageInfo

func (m *DelayedWithdrawalRecord) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *DelayedWithdrawalRecord) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *DelayedWithdrawalRecord) GetUnlockTimestamp() int64 {
	if m != nil {
		return m.UnlockTimestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*DelayedWithdrawalRecord)(nil), "moca.payment.DelayedWithdrawalRecord")
}

func init() {
	proto.RegisterFile("moca/payment/delayed_withdrawal_record.proto", fileDescriptor_5bf591a176352bb4)
}

var fileDescriptor_5bf591a176352bb4 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xc9, 0xcd, 0x4f, 0x4e,
	0xd4, 0x2f, 0x48, 0xac, 0xcc, 0x4d, 0xcd, 0x2b, 0xd1, 0x4f, 0x49, 0xcd, 0x49, 0xac, 0x4c, 0x4d,
	0x89, 0x2f, 0xcf, 0x2c, 0xc9, 0x48, 0x29, 0x4a, 0x2c, 0x4f, 0xcc, 0x89, 0x2f, 0x4a, 0x4d, 0xce,
	0x2f, 0x4a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x01, 0xa9, 0xd6, 0x83, 0xaa, 0x96,
	0x12, 0x4c, 0xcc, 0xcd, 0xcc, 0xcb, 0xd7, 0x07, 0x93, 0x10, 0x05, 0x52, 0x92, 0xc9, 0xf9, 0xc5,
	0xb9, 0xf9, 0xc5, 0xf1, 0x60, 0x9e, 0x3e, 0x84, 0x03, 0x95, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x87,
	0x88, 0x83, 0x58, 0x10, 0x51, 0xa5, 0x19, 0x4c, 0x5c, 0xe2, 0x2e, 0x10, 0x5b, 0xc3, 0xe1, 0x96,
	0x06, 0x81, 0xed, 0x14, 0xd2, 0xe1, 0x62, 0x49, 0x4c, 0x49, 0x29, 0x92, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x74, 0x92, 0xb8, 0xb4, 0x45, 0x57, 0x04, 0x6a, 0xa2, 0x63, 0x4a, 0x4a, 0x51, 0x6a, 0x71,
	0x71, 0x70, 0x49, 0x51, 0x66, 0x5e, 0x7a, 0x10, 0x58, 0x95, 0x90, 0x07, 0x17, 0x5b, 0x62, 0x6e,
	0x7e, 0x69, 0x5e, 0x89, 0x04, 0x13, 0x58, 0xbd, 0xc1, 0x89, 0x7b, 0xf2, 0x0c, 0xb7, 0xee, 0xc9,
	0x8b, 0x42, 0xf4, 0x14, 0xa7, 0x64, 0xeb, 0x65, 0xe6, 0xeb, 0xe7, 0x26, 0x96, 0x64, 0xe8, 0x79,
	0xe6, 0x95, 0x5c, 0xda, 0xa2, 0xcb, 0x05, 0x35, 0xcc, 0x33, 0xaf, 0x64, 0xc5, 0xf3, 0x0d, 0x5a,
	0x8c, 0x41, 0x50, 0xfd, 0x20, 0x7b, 0xd3, 0x8a, 0xf2, 0x73, 0x25, 0x98, 0x09, 0xd9, 0x0b, 0x52,
	0x25, 0xa4, 0xc9, 0x25, 0x50, 0x9a, 0x97, 0x93, 0x9f, 0x9c, 0x1d, 0x5f, 0x92, 0x99, 0x9b, 0x5a,
	0x5c, 0x92, 0x98, 0x5b, 0x20, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x1c, 0xc4, 0x0f, 0x11, 0x0f, 0x81,
	0x09, 0x5b, 0xe9, 0x74, 0x3d, 0xdf, 0xa0, 0xa5, 0x9e, 0x5a, 0x96, 0x9b, 0x5f, 0xac, 0x5f, 0x01,
	0x0f, 0x74, 0x1c, 0xde, 0x77, 0x72, 0x39, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07,
	0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86,
	0x28, 0xad, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0x88, 0x69, 0x10,
	0xb2, 0xcc, 0xd0, 0x08, 0xc9, 0xdc, 0x92, 0xca, 0x82, 0xd4, 0xe2, 0x24, 0x36, 0x70, 0x38, 0x1b,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x69, 0xac, 0xc0, 0xe9, 0x01, 0x00, 0x00,
}

func (m *DelayedWithdrawalRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelayedWithdrawalRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelayedWithdrawalRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UnlockTimestamp != 0 {
		i = encodeVarintDelayedWithdrawalRecord(dAtA, i, uint64(m.UnlockTimestamp))
		i--
		dAtA[i] = 0x20
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintDelayedWithdrawalRecord(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDelayedWithdrawalRecord(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Addr) > 0 {
		i -= len(m.Addr)
		copy(dAtA[i:], m.Addr)
		i = encodeVarintDelayedWithdrawalRecord(dAtA, i, uint64(len(m.Addr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDelayedWithdrawalRecord(dAtA []byte, offset int, v uint64) int {
	offset -= sovDelayedWithdrawalRecord(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DelayedWithdrawalRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Addr)
	if l > 0 {
		n += 1 + l + sovDelayedWithdrawalRecord(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovDelayedWithdrawalRecord(uint64(l))
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovDelayedWithdrawalRecord(uint64(l))
	}
	if m.UnlockTimestamp != 0 {
		n += 1 + sovDelayedWithdrawalRecord(uint64(m.UnlockTimestamp))
	}
	return n
}

func sovDelayedWithdrawalRecord(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDelayedWithdrawalRecord(x uint64) (n int) {
	return sovDelayedWithdrawalRecord(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DelayedWithdrawalRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDelayedWithdrawalRecord
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelayedWithdrawalRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelayedWithdrawalRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelayedWithdrawalRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDelayedWithdrawalRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDelayedWithdrawalRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelayedWithdrawalRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDelayedWithdrawalRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDelayedWithdrawalRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelayedWithdrawalRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDelayedWithdrawalRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDelayedWithdrawalRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnlockTimestamp", wireType)
			}
			m.UnlockTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelayedWithdrawalRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnlockTimestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDelayedWithdrawalRecord(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDelayedWithdrawalRecord
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDelayedWithdrawalRecord(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDelayedWithdrawalRecord
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDelayedWithdrawalRecord
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDelayedWithdrawalRecord
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDelayedWithdrawalRecord
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDelayedWithdrawalRecord
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDelayedWithdrawalRecord
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDelayedWithdrawalRecord        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDelayedWithdrawalRecord          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDelayedWithdrawalRecord = fmt.Errorf("proto: unexpected end of group")
)
